### ISSUE TITLE
Missing Issue Background XML tag stops script

### ISSUE THREAD

**Issue by stansteenhuis** [packetfocus/BurpParser#18]
Some of the Burp extensions do not generate <issue background> verbiage.   When the tag is missing, execution stops.  
Traceback (most recent call last):
  File "BurpXMLParser.py", line 518, in <module>
    main()
  File "BurpXMLParser.py", line 495, in main
    process(xmlFileIn)
  File "BurpXMLParser.py", line 217, in process
    issueBackground = i.find('issuebackground').text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by Caprico1** [comment]
line 217 on adding a try block seems to have worked.

```
         try:
            issueBackground = i.find('issuebackground').text
            issueBackground = str(issueBackground)

            # have to replace commas before making csv. Replaced with | for now.
            issueBackground = strip_tags(issueBackground)
            # this was a fix for the CSV outfile. Need to rethink the order of this.
            issueBackground = issueBackground.replace(',', "|")
        except:
            pass
```
